name: Ruby

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        postgres_version: [9, 10, 11, 12]

    services:
      postgres:
        image: postgres:${{ matrix.postgres_version }}
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: "postgres://postgres@localhost/que_locks"
      PGHOST: 127.0.0.1
      PGUSER: postgres

    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Install system dependencies
        run: |
          sudo apt-get -yqq install libpq-dev postgresql-client
          createdb que_locks
      - name: Build and test with Rake
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rake
  lint:
    runs-on: ubuntu-latest

    env:
      PGHOST: 127.0.0.1
      PGUSER: postgres

    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Install system dependencies
        run: |
          sudo apt-get -yqq install libpq-dev postgresql-client
      - name: Bundle
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Check code with rubocop
        run: |
          bundle exec rubocop
      - name: Check code formatting with rufo
        run: |
          bundle exec rufo --check lib test
